# ruff: noqa: E501

BUILDING_2016 = {
    "Access Limitations": "",
    "Architect": "ZAS Architects",
    "Architectural Style": "Contemporary (1995 – Present)",
    "Bldg Construction": "Built after 2000",
    "Building Address": "11 Arboretum Ln.",
    "Building Description": "This centre is not just another school building - it has big open spaces for student interaction, labs that inspire collaboration and no lecture halls. It opened in the fall of 2015. The building is the home of the student Renaissance Engineer, a creative problem solver and entrepreneurial leader with a social conscience. Its cloud-like triangular glass façade stands bold, composed of a series of triangles positioned according to a custom-designed algorithm. Because of the reflection of light and pattern across campus, the building has been nicknamed 'the Cloud.' Inside, the five-story building houses Design Commons for fostering entrepreneurial ideas. A massive multi-storey materials testing lab provides an unprecedented hands-on approach to both learning and teaching.",
    "Building Name": "York University - Bergeron Centre for Engineering Excellence",
    "Eighth Tour": "",
    "Eleventh Tour": "",
    "Extension": None,
    "Facebook": "https://www.facebook.com/lassondeschool/?ref=hl",
    "Family-Friendly": "Yes",
    "Fifteenth Tour": "",
    "Fifth Tour": "",
    "Filming Tripod": "Yes",
    "First Tour": "",
    "Flickr": "",
    "Fourteenth Tour": "",
    "Fourth Tour": "",
    "Fully Accessible": "Yes",
    "Guide Tours": "No",
    "Instagram": "https://www.instagram.com/lassondeschool/?hl=en",
    "Interior Filming": "Yes",
    "Interior Photog Tripod": "Yes",
    "Interior Photography": "Yes",
    "LEED Cert": "No",
    "Latitude": 43.772453,
    "Location Instructions": "",
    "Longitude": -79.511288,
    "Main Purpose": "Architecture & Design",
    "Ninth Tour": "",
    "Parking (Free)": "No",
    "Parking (Paid)": "Yes",
    "Partially Accessible": "No",
    "Postal Code": "M3J 1P3",
    "Programming Theme": "No",
    "Public washrooms": "Yes",
    "Sat Last Entry": "4:30",
    "Saturday Hours": "10:00 am to 5:00 pm",
    "Second Tour": "",
    "Seventh Tour": "",
    "Sixteenth Tour": "",
    "Sixth Tour": "",
    "Suite/Floor": "",
    "Sun Last Entry": "4:30",
    "Sunday Hours": "10:00 am to 5:00 pm",
    "Telephone": "416-736-5484",
    "Tenth Tour": "",
    "Third Tour": "",
    "Thirteenth Tour": "",
    "Twelfth Tour": "",
    "Twitter": "https://twitter.com/LassondeSchool",
    "Visitor Experience": "Visitors can expect an inspiring and all-encompassing environment. The building's labs, collaborative spaces and social areas will be open to the public. Experience the stunning façade, reflecting natural light and vistas of western Toronto from the Bergeron Centre rooftop space. Tours of the building will be available for interested visitors, highlighting both the architectural elements and the educational benefits of the new space. There will be activities for adults and children where they will be encouraged to take part in the 'maker culture' that Lassonde School of Engineering is building. These activities will inspire and draw out visitors' inner engineer.",
    "Website": "http://lassonde.yorku.ca/",
    "Year Constructed": "2015",
    "YouTube": "https://www.youtube.com/user/lassondeschool",
    "_id": 139,
}

BUILDING_2017 = {
    "Access Limitations": "",
    "Architect": "Unknown",
    "Architectural Style": "Edwardian (1900-1916)",
    "Bldg Construction": "Built 1900-1910",
    "Building Address": "70 Jefferson Ave.",
    "Building Description": "Media pioneer Moses Znaimer (Citytv, MuchMusic, Bravo etc.) opened The ZoomerPlex in 2012, a 2.6 acre media, production, and live event complex in Liberty Village. ZoomerMedia\x7fs multi-media operation  includes television channels like VisionTV, radio stations like The New Classical 96.3 FM and AM 740/96.7 FM \x7f Zoomer Radio, the flagship Zoomer magazine, and the MZTV Museum of Television \x7f the world\x7fs largest private collection of rare pre-war and vintage television sets.",
    "Building Name": "ZoomerPlex",
    "Building Type": "Media / Broadcaster Facility",
    "Eighth Tour": "",
    "Eleventh Tour": "",
    "Extension": "www.zoomermedia.ca",
    "Facebook": "http://facebook.com/everythingzoomer",
    "Family-Friendly": "Yes",
    "Fifteenth Tour": "",
    "Fifth Tour": "",
    "Filming Tripod": "Yes",
    "First Tour": "",
    "Flickr": "",
    "Fourteenth Tour": "",
    "Fourth Tour": "",
    "Fully Accessible": "Yes",
    "Guide Tours": "Yes",
    "Instagram": "",
    "Interior Filming": "Yes",
    "Interior Photog Tripod": "Yes",
    "Interior Photography": "Yes",
    "LEED Cert": "No",
    "Latitude": 43.63793606,
    "Location Instructions": "",
    "Longitude": -79.42182447,
    "New": "No",
    "Ninth Tour": "",
    "Parking (Free)": "Yes",
    "Parking (Paid)": "No",
    "Partially Accessible": "No",
    "Postal Code": "M6K 1Y4",
    "Public washrooms": "Yes",
    "Sat Last Entry": "4:30",
    "Saturday Hours": "10:00 am to 5:00 pm",
    "Second Tour": "",
    "Seventh Tour": "",
    "Sixteenth Tour": "",
    "Sixth Tour": "",
    "Suite/Floor": "",
    "Sun Last Entry": "",
    "Sunday Hours": "",
    "Telephone": "416-367-5353",
    "Tenth Tour": "",
    "Third Tour": "",
    "Thirteenth Tour": "",
    "Twelfth Tour": "",
    "Twitter": "http://twitter.com/zoomer",
    "Visitor Experience": "Visitors will see Moses' MZTV Museum of Television, which includes television sets owned by Marilyn Monroe and Elvis Presley, 1920s mechanical scanning discs, Felix the Cat, and the 1939 World\x7fs Fair \x7fPhantom Teleceiver\x7f \x7f the lucite set that introduced commercial television to North America at the 1939 World Fair in New York City. Pick up your complimentary copy of Zoomer magazine, hang out with your favourite radio jocks as they broadcast live, and tour Zoomer Hall.",
    "Website": "http://www.zoomermedia.ca",
    "Year Constructed": "Unknown",
    "YouTube": "",
    "_id": 134,
}

BUILDING_2018 = {
    "Access Limitations": "Stair only access to the studio; no elevator; steep stairs. ",
    "Architect": "Unknown",
    "Architectural Style": "Commercial/Industrial",
    "Bldg Construction": "Built 1910-1919",
    "Building Address": "25a Morrow Ave.",
    "Building Description": "The Canadian Hanson and Van Winkle Company Limited building served as the head office and manufacturing plant for the fabrication of steel and metals, with a specialization in the installation and plating of polishing equipment.  The extensive facility also included a thoroughly equipped laboratory and demonstrating department for the trade. During the Second World War, the Hanson and Van Winkle Building was used for the strategic manufacturing of war weapons.  Today, the building houses a collection of arts and culture businesses including the architecture studio of Atelier Kastelic Buffey (AKB). ",
    "Building Name": "Atelier Kastelic Buffey",
    "Building Type": "Architecture & Design",
    "Eighth Tour": "",
    "Eleventh Tour": "",
    "Extension": "1,2,3,4 or 5",
    "Facebook": "http://www.facebook.com/atelierkastelicbuffey/",
    "Family-Friendly": "No",
    "Fifteenth Tour": "",
    "Fifth Tour": "",
    "Filming Tripod": "No",
    "First Tour": "",
    "Flickr": "",
    "Fourteenth Tour": "",
    "Fourth Tour": "",
    "Fully Accessible": "No",
    "Guide Tours": "No",
    "Instagram": "https://instagram.com/atelier.kastelicbuffey/",
    "Interior Filming": "No",
    "Interior Photog Tripod": "No",
    "Interior Photography": "No",
    "LEED Cert": "No",
    "Latitude": 43.65290471,
    "Location Instructions": "",
    "Longitude": -79.44651762,
    "New": "Yes",
    "Ninth Tour": "",
    "Parking (Free)": "Yes",
    "Parking (Paid)": "No",
    "Partially Accessible": "Yes",
    "Postal Code": "M6R 2H9",
    "Public washrooms": "No",
    "Sat Last Entry": "4:30",
    "Saturday Hours": "10:00 am to 5:00 pm",
    "Second Tour": "",
    "Seventh Tour": "",
    "Sixteenth Tour": "",
    "Sixth Tour": "",
    "Suite/Floor": "202",
    "Sun Last Entry": "4:30",
    "Sunday Hours": "10:00 am to 5:00 pm",
    "Telephone": "416-204-1331",
    "Tenth Tour": "",
    "Third Tour": "",
    "Thirteenth Tour": "",
    "Twelfth Tour": "",
    "Twitter": "",
    "Visitor Experience": "Guests will see inside an award-winning, internationally renown, small-scale architectural office, AKB, led by husband and wife team Robert Kastelic and Kelly Buffey.  An open concept loft-like workspace with timber frame construction, exposed brickwork and large industrial windows with boardroom, meeting room and library.  Materials, models, sketches, conceptual and construction drawings will be presented and members of the architectural team will be available for questions, explanation and/or discussions throughout the day. AKB is part of the Toronto Society of Architects' Open Studio program. For more information visit the special project's webpage. ",
    "Website": "http://www.akb.ca",
    "Year Constructed": "1912",
    "YouTube": "",
    "_id": 11,
}

BUILDING_ADDRESS_2019 = {
    "dot_postal": "M5V 3A8",
    "dot_Longitude": "-79.3947484327",
    "dot_suiteFloor": "111",
    "dot_buildingAddress": "401 Richmond Street West",
    "dot_phone": "416-595-5900",
    "dot_Latitude": "43.6477554326",
    "dot_phoneExt": "",
}

BUILDING_LINKS_2019 = {
    "dot_youTube": "http://",
    "dot_flickr": "http://www.flickr.com/photos/401richmond/",
    "dot_url": "http://urbanspace.org",
    "dot_imageCredit": "",
    "dot_image": "401_Richmond.jpg",
    "dot_twitter": "http://twitter.com/401richmond",
    "dot_instagram": "http://instagram.com/401richmond",
    "dot_faceBook": "http://www.facebook.com/401richmond/",
}

BUILDING_ARCHITECTURE_2019 = {
    "dot_type": ["Arts & Cultural Centre"],
    "dot_year": "1899",
    "dot_originalArchitect": "John Wilson Siddall",
    "dot_style": ["Commercial/Industrial"],
    "dot_buildingConstructionRange": "Built 1920-1929",
}

BUILDING_2019 = {
    "dot_ProgramGuideDescription": [
        "@401richmond is an award-winning restored industrial building that is now a thriving arts and culture hub."
    ],
    "dot_FullDescription": [
        "401 Richmond is a heritage-designated industrial building transformed into an arts and culture hub. The building was originally constructed in several phases between 1899 and 1923 for the Macdonald Manufacturing Company. The building operated as a tin factory best known for its lithographic work. That artistic lineage is still seen today with a community of nearly 150 artists, cultural producers, nonprofits and microenterprises."
    ],
    "dot_Tours": {
        "dot_guided": "Yes",
        "dot_StartTime9": "",
        "dot_StartTime14": "",
        "dot_StartTime15": "",
        "dot_StartTime16": "",
        "dot_Duration1": "01Hrs 30Min",
        "dot_StartTime10": "",
        "dot_StartTime11": "",
        "dot_StartTime12": "",
        "dot_StartTime13": "",
        "dot_Duration5": "",
        "dot_Duration4": "",
        "dot_NonScheduled": "",
        "dot_Duration3": "00Hrs 30Min",
        "dot_Duration2": "00Hrs 30Min",
        "dot_Duration9": "",
        "dot_Duration8": "",
        "dot_Duration7": "",
        "dot_Duration6": "",
        "dot_Duration15": "",
        "dot_Duration16": "",
        "dot_Duration13": "",
        "dot_Duration14": "",
        "dot_Duration11": "",
        "dot_Duration12": "",
        "dot_Duration10": "",
        "dot_StartTime3": "3:00 pm",
        "dot_StartTime4": "",
        "dot_StartTime1": "11:00 am",
        "dot_StartTime2": "1:00 pm",
        "dot_StartTime7": "",
        "dot_StartTime8": "",
        "dot_StartTime5": "",
        "dot_StartTime6": "",
    },
    "dot_Days": {
        "dot_openSaturday": "Yes",
        "dot_SaturdayStart": "10:00 am",
        "dot_SundayClose": "",
        "dot_openSunday": "No",
        "dot_SundayLastAdmit": "",
        "dot_SaturdayLastAdmit": "4:30 pm",
        "dot_SundayStart": "",
        "dot_SaturdayClose": "5:00 pm",
    },
    "dot_VisitorExperience": [
        "Visitors will have an opportunity to visit the rooftop garden and to explore the building. Guided tours will be offered of both the rooftop garden and the galleries. People will be available to speak to the history of the building and to the arts and culture community."
    ],
    "dot_Links": BUILDING_LINKS_2019,
    "dot_Features": {
        "dot_Washrooms": "Yes",
        "dot_AccessiblePartial": "No",
        "dot_InfoCentre": "No",
        "dot_ParkingFree": "No",
        "dot_ParkingPaid": "Yes",
        "dot_LEED": "No",
        "dot_New": "No",
        "dot_InteriorPhotographyTripod": "Yes",
        "dot_InteriorFilmingTripod": "Yes",
        "dot_buildingLimitation": [
            "Our Northeast entrance is fully accessible. Accessible washrooms located on the first and fourth floors. Elevator access is available. There is a portable ramp in place to access the roof top garden."
        ],
        "dot_InteriorFilming": "Yes",
        "dot_InteriorPhotography": "Yes",
        "dot_FamilyFriendly": "Yes",
        "dot_Theme": "Yes",
        "dot_AccessibleFull": "Yes",
    },
    "dot_specialInstructions": "",
    "dot_Address": BUILDING_ADDRESS_2019,
    "dot_buildingName": "401 Richmond",
    "dot_locationDetails": [],
    "dot_numSort": "401",
    "dot_Architecture": BUILDING_ARCHITECTURE_2019,
    "dot_documentID": "9147A2C95A5E9F0985258398005B445B",
}
